M48
; DRILL file {KiCad 7.0.2-0} date 2023 September 22, Friday 15:46:37
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-22T15:46:37+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X4.471Y14.537
T2
X5.021Y9.886
X8.822Y9.886
T3
X6.858Y26.162
T0
M30
