M48
; DRILL file {KiCad (7.0.0)} date Thu Sep 21 17:16:24 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-21T17:16:24+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
%
G90
G05
T1
X50.8Y18.99
X50.8Y11.49
T2
X29.959Y63.504
X29.959Y48.514
X29.959Y29.718
X29.959Y14.728
T0
M30
